//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class elemento
    {
        public int id_elemento { get; set; }
        public string nombre_elemento { get; set; }
        public double precio { get; set; }
        public string descripcion { get; set; }
        public int seccion { get; set; }
    
        public virtual seccion seccion1 { get; set; }
    }
}
